version: 0.2

phases:
  build:
    commands:
      - aws s3 sync s3-files/template/ s3://${bucket}/template --delete --exact-timestamps
      - aws s3 sync s3-files/inc/ s3://${bucket}/inc --delete --exact-timestamps
      - aws s3 cp s3-files/index.html s3://${bucket}/index.html
