version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install zip
  build:
    commands:
      - cd lambda
      - pip install -r requirements.txt -t .
      - zip -q -r ../lambda.zip ./*
artifacts:
  files:
    - '**/*'
  base-directory: lambda
